services:
    postgres:
        image: postgres:15
        container_name: sysacad_postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "3000:${POSTGRES_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
